#ifndef HUNTSMAN_USB_DEVICE_CONFIG_H
#define HUNTSMAN_USB_DEVICE_CONFIG_H

#define USB_DEVICE_CONFIG_KHCI              0
#define USB_DEVICE_CONFIG_EHCI              0
#define USB_DEVICE_CONFIG_LPCIP3511FS       0
#define USB_DEVICE_CONFIG_LPCIP3511HS       1
#define USB_DEVICE_CONFIG_NUM               1
#define USB_DEVICE_CONFIG_HID               2
#define USB_DEVICE_CONFIG_AUDIO             0
#define USB_DEVICE_CONFIG_AUDIO_CLASS_2_0   0
#define USB_DEVICE_CONFIG_CDC_ACM           0
#define USB_DEVICE_CONFIG_CDC_ECM           0
#define USB_DEVICE_CONFIG_CDC_RNDIS         0
#define USB_DEVICE_CONFIG_MSC               0
#define USB_DEVICE_CONFIG_MTP               0
#define USB_DEVICE_CONFIG_PHDC              0
#define USB_DEVICE_CONFIG_VIDEO             0
#define USB_DEVICE_CONFIG_PRINTER           0
#define USB_DEVICE_CONFIG_DFU               0
#define USB_DEVICE_CONFIG_CCID              0
#define USB_DEVICE_CONFIG_ENDPOINTS         6
#define USB_DEVICE_CONFIG_SELF_POWER        0
#define USB_DEVICE_CONFIG_REMOTE_WAKEUP     1
#define USB_DEVICE_CONFIG_USE_TASK          0
#define USB_DEVICE_CONFIG_SOF_NOTIFICATIONS 0
#define USB_DEVICE_CONFIG_GET_SOF_COUNT     0
#define USB_DEVICE_CONFIG_CHARGER_DETECT    0
#define USB_DEVICE_CONFIG_DETACH_ENABLE     0
#define USB_DEVICE_CONFIG_RETURN_VALUE_CHECK 0
#define USB_DEVICE_CONFIG_LOW_POWER_MODE    0
#define USB_DEVICE_CONFIG_LPM_L1            0
#define USB_DEVICE_CONFIG_USB20_TEST_MODE   0
#define USB_DEVICE_CONFIG_ROOT2_TEST        0
#define USB_DEVICE_CONFIG_OTG               0

#define USB_DEVICE_INTERRUPT_PRIORITY       3u
#define USB_DEVICE_CONFIG_ENDPOINTS_MAX     USB_DEVICE_CONFIG_ENDPOINTS
#define USB_STACK_USE_DEDICATED_RAM         1

#endif
