#!/usr/bin/env python3
"""Extract keyboard facts by running production scatter initialization read-only."""
import argparse
from pathlib import Path

from production_arm import ProductionArm
from firmware_defaults import initializer


def render(reference):
    p = ProductionArm(reference)
    output = ['#include "defaults.h"',
              '/* Generated by tools/keyboard_reference_tables.py from the hash-pinned',
              ' * production image; do not substitute a physical row-order guess. */',
              '#include "huntsman_layout.h"', '']
    for name, ctype, address, count, width in (
        ('g_keyboard_grid', 'keyboard_grid_cell_t', 0x20020800, 72, 5),
        ('g_keyboard_base', 'keyboard_action_t', 0x200252a5, 135, 8),
        ('g_keyboard_fn_ansi', 'keyboard_action_t', 0x200256dd, 135, 8),
        ('g_keyboard_fn_iso', 'keyboard_action_t', 0x2001b91c, 135, 8),
        ('g_keyboard_fn_jis', 'keyboard_action_t', 0x2001b4e4, 135, 8),
    ):
        output.append(f'/* Production address 0x{address:08x}. */')
        output.append(f'const {ctype} {name}[{count}] = {{')
        for i in range(count):
            row = p.read(address + i * width, width)
            output.append('    {' + ', '.join(f'0x{x:02x}' for x in row) + '},')
        output.extend(['};', ''])
    for name, address in (('g_actuation_levels', 0x2001b486), ('g_rapid_levels', 0x2001dd7a)):
        output.append(f'/* Production address 0x{address:08x}; entry zero is not a selectable level. */')
        values = [int.from_bytes(p.read(address + i * 2, 2), 'little') for i in range(11)]
        macro = 'DEFAULT_ACTUATION_LEVELS' if name == 'g_actuation_levels' else 'DEFAULT_RAPID_LEVELS'
        assert initializer(macro) == values, f'{macro} differs from the reference'
        output.append(f'const uint16_t {name}[11] = {macro};')
        output.append('')
    return '\n'.join(output)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('reference')
    parser.add_argument('--check', type=Path)
    args = parser.parse_args()
    content = render(args.reference)
    if args.check:
        assert args.check.read_text() == content, 'keyboard tables differ from production'
        print('PASS keyboard grid, all layout layers, and threshold tables match production')
    else:
        print(content, end='')
