# A runnable reference port, with no extraction, Huntsman or SDK dependency.
add_library(midi_typist_app OBJECT ${MT_APP_SOURCES})
target_include_directories(midi_typist_app PUBLIC firmware/app/include)
target_compile_definitions(midi_typist_app PUBLIC MT_KEY_CAPACITY=128 MT_LIGHT_FRAME_BYTES=384)
target_compile_options(midi_typist_app PRIVATE -Wall -Wextra -Werror)
add_library(synthetic_board STATIC ${MT_BOARD_DIR}/src/synthetic_board.c)
target_include_directories(synthetic_board PUBLIC ${MT_BOARD_DIR}/include firmware/app/include)
target_compile_definitions(synthetic_board PUBLIC MT_KEY_CAPACITY=128 MT_LIGHT_FRAME_BYTES=384)
target_compile_options(synthetic_board PRIVATE -Wall -Wextra -Werror)
add_executable(midi_typist_sim ${MT_BOARD_DIR}/src/main.c)
target_link_libraries(midi_typist_sim PRIVATE midi_typist_app synthetic_board)
target_compile_options(midi_typist_sim PRIVATE -Wall -Wextra -Werror)
enable_testing()
add_executable(portable_app_tests tests/test_portable_app.c)
target_link_libraries(portable_app_tests PRIVATE midi_typist_app synthetic_board)
target_compile_options(portable_app_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME portable_app COMMAND portable_app_tests)
add_test(NAME portability_architecture COMMAND python3 -B ${CMAKE_CURRENT_SOURCE_DIR}/tools/test_portability.py)
add_test(NAME defaults COMMAND python3 -B ${CMAKE_CURRENT_SOURCE_DIR}/tools/test_defaults.py)
